### PR TITLE
Suport for multiple album and track artists

### PR DESCRIPTION
**Pull request by lutzbuerkle**
I added support for multiple album and track artists. This is very common e.g. in classical music. See album_id=4322228 for example

### CODE REVIEW

**Comment by lutzbuerkle** [comment]
The artists list contains all artists of an album or track, respectively. Generally, there are at least two different types of artists: MAIN and FEATURED.

For example `album = session.get_album(4322228)` returns the following list of artists:
Barbara Bonney, MAIN
Anne Sofie von Otter, FEATURED
Hans Peter Blochwitz, FEATURED
Sir Willard White, FEATURED
English Baroque Soloists, FEATURED
The Monteverdi Choir, FEATURED
John Eliot Gardiner, FEATURED
while artist contains only the MAIN artist (in this case 'Barbara Bonney')

**Comment by tamland** [comment]
Ok, I think `MAIN`/`FEATURED` should be mapped to an enum or a readable name (the former would probably be better) and not exposed directly to the caller. Otherwise there is no way for people to know what it might contain without checking the api output.

And "role" for instance would be a more descriptive name to use here.

**Comment by lutzbuerkle** [comment]
Done!

**Comment by tamland** [comment]
Thanks!

**Pull request merged**
