### PR TITLE
Bug fix in load_oauth_session

### PR DESCRIPTION
**Pull request by lutzbuerkle**
After the session tokens have been refreshed successfully, `request.basic_request('GET', 'sessions')` has to be called once again to retrieve `countryCode` and `userId`

### CODE REVIEW

**Comment by morguldir** [comment]
I fixed this initially last night, but didn't have time to finish it, i probably should have opened an issue for it.

Anyway i think it's better if the token_refresh is done whenever a request says that the token has expired, this allows the token to be refreshed if it runs out while a program is running. I have added this now in ee120d94d897f6f6ee644fd835a35fb68942b331

**Comment by lutzbuerkle** [comment]
Perfect, this is definitely a better solution

**Comment by yungwarlock** [comment]
Please. How does a refresh_token last till it'll need to be recreated

**Comment by morguldir** [comment]
> Please. How does a refresh_token last till it'll need to be recreated

Until you log out as far as I know, ideally they could send a new refresh token on use, so that you can only use the old one once, but they seem to not have implemented that yet

**Pull request closed without merging**
