### PR TITLE
Fixed wrong determination of file extensions. Fixes tamland/python-ti…

### PR DESCRIPTION
**Pull request by exislow**
…dal#304

### CODE REVIEW

**Comment by tehkillerbee** [comment]
This looks like a better solution. I struggled with the same issue and ended up with the current (wrong) implementation when deciding which file extension to use.

This might break some of the unit tests though. Have you checked if they still pass? (make test)

**Comment by exislow** [comment]
I was wondering, if it is possible to get this PR as a hotfix release anytime soon? Maybe also together with my other PR #303 

Thanks!

**Comment by exislow** [comment]
@tamland: Anything else I can help with?

**Comment by tehkillerbee** [comment]
Thanks, LGTM! Merged. :+1:

**Pull request merged**
