### PR TITLE
[#129] Quick fix for "got key error 'picture'" error.

### PR DESCRIPTION
**Pull request by BlackLight**
The error started to pop up recently in the API (see #129).

A proper fix would probably involve taking a look at the returned JSON object to verify if the attribute name has changed, but this should get things back to work for now.

### CODE REVIEW

**Comment by nickbp** [comment]
I'm not seeing a `picture` field in the JSON response at all, so maybe they just removed the field entirely.

In any case applying this patch fixed the error that I had recently started seeing:
```
  File "tidalapi/session.py", line 282, in load_oauth_session
    self.user = tidalapi.User(self, user_id=json['userId']).factory()
  File "tidalapi/user.py", line 48, in factory
    return self.request.map_request('users/%s' % self.id, parse=self.parse)
  File "tidalapi/request.py", line 118, in map_request
    return self.map_json(json_obj, parse=parse)
```

**Comment by Lauravdsanden** [comment]
> 

How does one use this patch in the scraping code?

**Comment by 2e0byo** [comment]
> How does one use this patch in the scraping code?

```shell
pip install git+https://github.com/BlackLight/python-tidal.git@129-login-failed-got-key-error-picture
```

**Comment by 2e0byo** [comment]
FWIW I'm not sure of the wisdom of using `''`: is it normally a link?  Maybe `None` to signal absence.  But a nit-pick as the real thing is find out where the picture has gone in the api or just drop it entirely.

**Comment by mrgodot** [comment]
I just ran into this same exception. The patch did the trick. Thank you!

**Comment by timrae** [comment]
@morguldir What do you think? Would be good to get an upstream fix for this problem.

**Review by tehkillerbee — APPROVED** [review]
Usually, I would prefer formatting related changes to be in a separate PR.

Anyways, looks good to me.

**Pull request merged**
