### PR TITLE
feat(mix): add mix images and tests

### PR DESCRIPTION
**Pull request by jozefKruszynski**
Added images to mix class, along with tests.

### CODE REVIEW

**Comment by 2e0byo** [comment]
Other than one nit looks good to me, thanks very much.

**Comment by jozefKruszynski** [comment]
> Other than one nit looks good to me, thanks very much.

One nit?

**Comment by 2e0byo** [comment]
> One nit?

I meant doctring (I left a comment).

It's not quite grammatical, perhaps 'the desired image width and height'?

Sorry for the delay: I got sick and then started a new job.

**Comment by jozefKruszynski** [comment]
No worries, I don’t see the comment but I see what you mean I think.
I copied that docstring from elsewhere in the code, but I'll take a look tomorrow and fix it

**Review by tehkillerbee — APPROVED** [review]

**Comment by tehkillerbee** [comment]
Thanks for the PR. Looks good to me! Merged.

**Pull request merged**
