### PR TITLE
feat(album): add type to album object, type is either ALBUM, COMPILATION, EP or SINGLE

### PR DESCRIPTION
**Pull request by jozefKruszynski**
add type to album object, type is either ALBUM, COMPILATION, EP or SINGLE

### CODE REVIEW

**Comment by 2e0byo** [comment]
Would you be able to add tests?  Just asserting against real tidal records would be fine.

**Comment by jozefKruszynski** [comment]
> Would you be able to add tests?  Just asserting against real tidal records would be fine.

Sorry, I should have added them before. I'll do it as soon as possible.

**Comment by 2e0byo** [comment]
No rush! thanks :)

**Comment by jozefKruszynski** [comment]
> No rush! thanks :)

Done

**Comment by 2e0byo** [comment]
Hanging off merging these until I get an evening to add autoreleasing, but will hopefully be this week; thanks for the work!

**Comment by tehkillerbee** [comment]
@2e0byo Setting you as reviewer, so you can control when to merge it.

**Comment by 2e0byo** [comment]
Great will try to get these in tomorrow.  Sorry for the galatial pace here.

**Comment by tehkillerbee** [comment]
@2e0byo No worries at all, take your time :)

**Comment by jozefKruszynski** [comment]
Any news on this one guys, it's the only thing stopping us from switching to the official release in Music Assistant.

**Comment by 2e0byo** [comment]
Sorry!  finally got some space and looked through python-tidal this weekend.

There's a lot of stuff I want to do as a first release actually: tests are broken, lots of cleanup needed.  I'll do a pr later but this can definitely be merged.  Auto-releasing can wait.

Thanks for your patience on this @jozefKruszynski.  I've made one trivial tweak; hope you don't mind. (`get` returns None by default if not present, so behavioour is the same).

**Comment by jozefKruszynski** [comment]
Thanks for the merge and the tweak.

**Pull request merged**
